import type { Preview } from "@storybook/react-vite"

// The package's own Tailwind entry, compiled by Vite's PostCSS pass (see
// postcss.config.mjs). This is the same file that builds dist/styles.css, so
// Storybook renders exactly what a consumer gets.
import "../src/styles/index.css"

const preview: Preview = {
  // Every component gets an autogenerated Docs page (usage + source snippets).
  tags: ["autodocs"],
  parameters: {
    layout: "centered",
    controls: {
      matchers: { color: /(background|color)$/i, date: /Date$/i },
    },
    backgrounds: {
      options: {
        offwhite: { name: "Off White", value: "#f6f7f1" },
        beige: { name: "Beige", value: "#eee6d8" },
        teal: { name: "Teal", value: "#1f4147" },
        green: { name: "Green", value: "#7dbe31" },
        white: { name: "White", value: "#ffffff" },
      },
    },
    // "error" fails the story (and CI) on an axe violation instead of just
    // annotating it. Opt an individual story out with `a11y: { test: "todo" }`
    // and a comment saying why — never flip this back globally.
    a11y: { test: "error" },
  },
  initialGlobals: {
    backgrounds: { value: "offwhite" },
  },
}

export default preview
